export const accountRes = [
  {
    id: "test_client_1",
    name: "John Doe 1",
    email: "johndoe@example.com",
    status: "active",
    login_users: [
      {
        id: "login_user_1",
        name: "Jane Smith",
        email: "janesmith@example.com",
        role: "admin",
        status: "inactive",
        login_at: new Date("2023-09-21T10:00:00Z"),
      },
      {
        id: "login_user_1",
        name: "Alice Johnson",
        email: "alicejohnson@example.com",
        role: "member",
        status: "active",
        login_at: new Date("2023-09-21T10:00:00Z"),
      },
    ],
    fee_type: "number",
    payment: {
      method: "card",
    },
    options: ["advanced"],
    expired_at: new Date("2025-12-31T23:59:59Z"),
    login_at: new Date("2024-10-21T10:00:00Z"),
  },
  {
    id: "test_client_2",
    name: "John Doe 2",
    email: "johndoe@example.com",
    status: "active",
    login_users: [
      {
        id: "login_user_1",
        name: "Jane Smith",
        email: "janesmith@example.com",
        role: "admin",
        status: "inactive",
        login_at: new Date("2024-10-21T10:00:00Z"),
      },
      {
        id: "login_user_1",
        name: "Alice Johnson",
        email: "alicejohnson@example.com",
        role: "admin",
        status: "active",
        login_at: new Date("2024-10-21T10:00:00Z"),
      },
    ],
    fee_type: "number",
    payment: {
      method: "card",
    },
    options: ["advanced"],
    expired_at: new Date("2025-12-31T23:59:59Z"),
    login_at: new Date("2024-10-21T10:00:00Z"),
  },
  {
    id: "test_client_3",
    name: "John Doe 3",
    email: "johndoe@example.com",
    status: "pending",
    login_users: [
      {
        id: "login_user_1",
        name: "Jane Smith",
        email: "janesmith@example.com",
        role: "admin",
        status: "inactive",
        login_at: new Date("2024-10-21T10:00:00Z"),
      },
      {
        id: "login_user_1",
        name: "Alice Johnson",
        email: "alicejohnson@example.com",
        role: "admin",
        status: "active",
        login_at: new Date("2024-10-21T10:00:00Z"),
      },
    ],
    fee_type: "number",
    payment: {
      method: "card",
    },
    options: ["advanced"],
    expired_at: new Date("2025-12-31T23:59:59Z"),
    login_at: new Date("2024-10-21T10:00:00Z"),
  },
  {
    id: "test_client_4",
    name: "John Doe 4",
    email: "johndoe@example.com",
    status: "inactive",
    login_users: [
      {
        id: "login_user_1",
        name: "Jane Smith",
        email: "janesmith@example.com",
        role: "admin",
        status: "inactive",
        login_at: new Date("2024-10-21T10:00:00Z"),
      },
      {
        id: "login_user_1",
        name: "Alice Johnson",
        email: "alicejohnson@example.com",
        role: "admin",
        status: "active",
        login_at: new Date("2024-10-21T10:00:00Z"),
      },
    ],
    fee_type: "number",
    payment: {
      method: "card",
    },
    options: ["advanced"],
    expired_at: new Date("2025-12-31T23:59:59Z"),
    login_at: new Date("2024-10-21T10:00:00Z"),
  },
  {
    id: "test_client_5",
    name: "John Doe 5",
    email: "johndoe@example.com",
    status: "active",
    login_users: [
      {
        id: "login_user_1",
        name: "Jane Smith",
        email: "janesmith@example.com",
        role: "admin",
        status: "inactive",
        login_at: new Date("2024-10-21T10:00:00Z"),
      },
      {
        id: "login_user_1",
        name: "Alice Johnson",
        email: "alicejohnson@example.com",
        role: "admin",
        status: "active",
        login_at: new Date("2024-10-21T10:00:00Z"),
      },
    ],
    fee_type: "number",
    payment: {
      method: "card",
    },
    options: ["advanced"],
    expired_at: new Date("2025-12-31T23:59:59Z"),
    login_at: new Date("2024-10-21T10:00:00Z"),
  },
];
